# Blog Requests

### GET status API
GET https://localhost:7209

### POST login
POST https://localhost:7209/v1/login

### Authorization by token, part 1. Retrieve and save token.
POST https://localhost:7209/v1/login
Content-Type: application/json

> {% client.global.set("auth_token", response.body.json.token); %}

### GET user
GET https://localhost:7209/v1/user
Authorization: Bearer {{auth_token}}

### GET author
GET https://localhost:7209/v1/author
Authorization: Bearer {{auth_token}}

### GET admin
GET https://localhost:7209/v1/admin
Authorization: Bearer {{auth_token}}

### GET categories
GET https://localhost:7209/v1/categories

### POST categories
POST https://localhost:7209/v1/categories
Content-Type: application/json

{
  "name": "",
  "slug": ""
}

### PUT categories
PUT https://localhost:7209/v1/categories/2
Content-Type: application/json

{
  "id": 2,
  "name": "Frontend",
  "slug": "frontend",
  "posts": []
}

### DELETE categories
DELETE https://localhost:7209/v1/categories/3

#------------------------------------
### GET
GET https://localhost:7199/

### GET
GET https://localhost:7199/Tiago Barbosa

### POST
POST https://localhost:7199/
Content-Type: application/json

{
  "id": 1,
  "username": "tiagobarbosa"
}

